### PR TITLE
Python port

### PR DESCRIPTION
**Pull request by mountaindust**
This should complete the Python port and basic testing for:
- Springs
- Beams
- Target Points
- Muscle-Model
- Mass Points
- Porous Structures  

3-Element Hill Muscle is untested, and Electrophysiology is not included. Any other recent updates to the MATLAB code are also not included. It would be a good idea to further test the included examples by comparing their output in VisIt.

### CODE REVIEW

**Comment by devangel77b** [comment]
Didnt' realize there was a python port going on. Is there anything I can help with?

**Comment by mountaindust** [comment]
Yes! There are definitely plenty of things that could be done. Here's a quick, off the top of my head laundry list:

- Fix 3-Element Hill Muscle. When I forked the repository, I was told 3-Element Hill was not working. I did not try to make it work in this port, and am not aware of whether or not it is now working in the MATLAB code. @nickabattista?

- Bring the port up to date with the MATLAB code. I see that Nick has been working on electrophysiology, but this is not in the Python port.

- I'm actually pretty happy with how fast the essential parts of the code run - I spent some time making sure I was leveraging NumPy as much as possible, and that has paid off: the HeartTube example seems to run just a bit faster than its MATLAB counterpart. Profiling the code reveals that the most expensive part by far is in string formatting and writing the results to file. Part of this is undoubtedly that Python 3.x treats all strings as unicode, which is a well-known and much argued over bottleneck. For my part, I chose 3.5 because I think (like it or not) Python 3.x is the present and future, and there are a lot of great benefits to coding in the latest version of Python. All that is to say, if I/O was instead handled by a C extension, it might speed up the code in a very significant way. If you feel like trying your hand at some C or C++, I suggest using Cython to build an I/O library Python extension and see what happens.

**Comment by devangel77b** [comment]
I'm familiar with Hill models and can take a stab at it if Nick wants me to; after that I can try C stuff (have done some of that too).  @nickabattista

**Comment by nickabattista** [comment]
Hi all! That'd be great! I don't think the 3-Element Hill model was fully incorporated. I believe the forcing function was never completed. I had that set as an undergraduate project, but they had decided not to join the group.

**Comment by mountaindust** [comment]
OK - Well, why don't you go ahead and merge my fork into your repository @nickabattista, and then @devangel77b can work off of a new fork from your master? Unless there are concerns with the current code, I'm done working on the Python port myself for now. Of course I'm happy to be available for consultation or bug fixes! I've noted that 3-Hill is likely broken in the Python README, so there shouldn't be any confusion there if someone clones your master repository.

**Comment by nickabattista** [comment]
Hi Christopher - sorry that took me so long to accept. I'm going to rename some of the subfolders to separate the matlab and python code.

**Comment by mountaindust** [comment]
No worries. I thought about doing some reorganization myself, but in the end, I figured it's better if you do it.

**Pull request merged**
